name: bootcamp_google
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  lottie: ^1.2.0
  flutter:
    sdk: flutter

  table_calendar: ^3.1.2
  fl_chart: ^0.68.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.2
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.0.2
  firebase_storage: ^11.6.9
  image_picker: ^1.0.7
  flutter_markdown: ^0.6.9
  google_generative_ai:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/images/kediIcon.png
    - assets/images/cuteCat.jpeg
    - assets/images/notLoginPageDesign.png
    - assets/images/cozyCats.jpg
    - assets/icons/chat.png
    - assets/icons/circle.png
    - .env
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo-Regular.ttf